import { average, pentagonFromMatches, winRate } from "@/lib/valorant/analysis"
import { buildPerformanceInsights } from "@/lib/valorant/performance"
import { buildRoundDetailInsights } from "@/lib/valorant/round-analysis"
import type { MatchDigest, PlayerLookup, PlayerProfile } from "@/lib/valorant/types"

export const SAMPLE_MATCHES: readonly MatchDigest[] = [
  {
    id: "demo-bind-001",
    mapName: "Bind",
    agent: "Jett",
    mode: "Competitive",
    result: "loss",
    score: "11-13",
    acs: 284,
    kills: 24,
    deaths: 17,
    assists: 4,
    kdRatio: 1.41,
    kast: 72,
    adr: 161,
    headshotRate: 31,
    tradeValue: 66,
    entryImpact: 84,
    postPlantImpact: 48,
    teamLuck: 28,
    narrative:
      "초반 진입과 교전 생산성은 높았지만 후반 post-plant 전환에서 팀 합류가 늦어졌습니다.",
    startedAt: "2026-07-03T12:40:00.000Z",
  },
  {
    id: "demo-ascent-002",
    mapName: "Ascent",
    agent: "Omen",
    mode: "Competitive",
    result: "win",
    score: "13-8",
    acs: 219,
    kills: 17,
    deaths: 13,
    assists: 7,
    kdRatio: 1.31,
    kast: 79,
    adr: 138,
    headshotRate: 27,
    tradeValue: 76,
    entryImpact: 52,
    postPlantImpact: 81,
    teamLuck: 62,
    narrative:
      "연막 유지와 retake 합류가 안정적이어서 낮은 교전량 대비 라운드 영향도가 높았습니다.",
    startedAt: "2026-07-03T10:15:00.000Z",
  },
  {
    id: "demo-lotus-003",
    mapName: "Lotus",
    agent: "Sova",
    mode: "Competitive",
    result: "win",
    score: "13-6",
    acs: 203,
    kills: 14,
    deaths: 10,
    assists: 12,
    kdRatio: 1.4,
    kast: 83,
    adr: 129,
    headshotRate: 24,
    tradeValue: 88,
    entryImpact: 49,
    postPlantImpact: 73,
    teamLuck: 67,
    narrative: "직접 킬보다 스캔 이후 트레이드 연결이 좋았고, 척후대 역할 기대치를 상회했습니다.",
    startedAt: "2026-07-02T21:05:00.000Z",
  },
]

export function buildMockProfile(lookup: PlayerLookup): PlayerProfile {
  return {
    displayName: lookup.name,
    tag: lookup.tag,
    region: lookup.region,
    accountLevel: 184,
    rank: "Ascendant 2",
    rr: 64,
    source: "mock",
    sourceLabel: "Mock fixture",
    consentState: "demo",
    summary: {
      matches: SAMPLE_MATCHES.length,
      winRate: winRate(SAMPLE_MATCHES),
      averageAcs: average(SAMPLE_MATCHES.map((match) => match.acs)),
      kills: SAMPLE_MATCHES.reduce((sum, match) => sum + match.kills, 0),
      deaths: SAMPLE_MATCHES.reduce((sum, match) => sum + match.deaths, 0),
      assists: SAMPLE_MATCHES.reduce((sum, match) => sum + match.assists, 0),
      kdRatio: 1.37,
      kast: average(SAMPLE_MATCHES.map((match) => match.kast)),
      adr: average(SAMPLE_MATCHES.map((match) => match.adr)),
      headshotRate: average(SAMPLE_MATCHES.map((match) => match.headshotRate)),
      teamLuck: average(SAMPLE_MATCHES.map((match) => match.teamLuck)),
      recentTeamLuck: average(SAMPLE_MATCHES.slice(0, 8).map((match) => match.teamLuck)),
    },
    pentagon: pentagonFromMatches(SAMPLE_MATCHES),
    insights: buildPerformanceInsights(SAMPLE_MATCHES, {
      storedMatches: SAMPLE_MATCHES.length,
      competitiveMatches: SAMPLE_MATCHES.length,
    }),
    roundDetails: buildRoundDetailInsights(lookup, []),
    recentMatches: SAMPLE_MATCHES,
  }
}
